/*
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class InjectionLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/moflon/emf/injection/parser/antlr/internal/InternalInjectionLanguage.tokens");
	}
}
