/**
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.injectionLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.moflon.emf.injection.injectionLanguage.ClassDeclaration;
import org.moflon.emf.injection.injectionLanguage.InjectionFile;
import org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Injection File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl#getClassDeclaration <em>Class Declaration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InjectionFileImpl extends MinimalEObjectImpl.Container implements InjectionFile
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<EObject> imports;

  /**
   * The cached value of the '{@link #getClassDeclaration() <em>Class Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassDeclaration()
   * @generated
   * @ordered
   */
  protected ClassDeclaration classDeclaration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InjectionFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return InjectionLanguagePackage.Literals.INJECTION_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EObject> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<EObject>(EObject.class, this, InjectionLanguagePackage.INJECTION_FILE__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassDeclaration getClassDeclaration()
  {
    return classDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClassDeclaration(ClassDeclaration newClassDeclaration, NotificationChain msgs)
  {
    ClassDeclaration oldClassDeclaration = classDeclaration;
    classDeclaration = newClassDeclaration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION, oldClassDeclaration, newClassDeclaration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setClassDeclaration(ClassDeclaration newClassDeclaration)
  {
    if (newClassDeclaration != classDeclaration)
    {
      NotificationChain msgs = null;
      if (classDeclaration != null)
        msgs = ((InternalEObject)classDeclaration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION, null, msgs);
      if (newClassDeclaration != null)
        msgs = ((InternalEObject)newClassDeclaration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION, null, msgs);
      msgs = basicSetClassDeclaration(newClassDeclaration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION, newClassDeclaration, newClassDeclaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case InjectionLanguagePackage.INJECTION_FILE__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION:
        return basicSetClassDeclaration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case InjectionLanguagePackage.INJECTION_FILE__IMPORTS:
        return getImports();
      case InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION:
        return getClassDeclaration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case InjectionLanguagePackage.INJECTION_FILE__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends EObject>)newValue);
        return;
      case InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION:
        setClassDeclaration((ClassDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case InjectionLanguagePackage.INJECTION_FILE__IMPORTS:
        getImports().clear();
        return;
      case InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION:
        setClassDeclaration((ClassDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case InjectionLanguagePackage.INJECTION_FILE__IMPORTS:
        return imports != null && !imports.isEmpty();
      case InjectionLanguagePackage.INJECTION_FILE__CLASS_DECLARATION:
        return classDeclaration != null;
    }
    return super.eIsSet(featureID);
  }

} //InjectionFileImpl
