/*
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractInjectionLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage.eINSTANCE);
		return result;
	}
}
