/*
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractInjectionLanguageScopeProvider extends DelegatingScopeProvider {
}
