/*
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.ui;

import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.moflon.emf.injection.ui.internal.InjectionActivator;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InjectionLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(InjectionActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		InjectionActivator activator = InjectionActivator.getInstance();
		return activator != null ? activator.getInjector(InjectionActivator.ORG_MOFLON_EMF_INJECTION_INJECTIONLANGUAGE) : null;
	}

}
