/*
 * generated by Xtext 2.34.0
 */
package org.moflon.tgg.mosl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TGGProposalProvider extends AbstractTGGProposalProvider {
}
