/**
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.injectionLanguage;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassName <em>Class Name</em>}</li>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassInjectionDeclaration <em>Class Injection Declaration</em>}</li>
 *   <li>{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getMethodDeclarations <em>Method Declarations</em>}</li>
 * </ul>
 *
 * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage#getClassDeclaration()
 * @model
 * @generated
 */
public interface ClassDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link org.moflon.emf.injection.injectionLanguage.JavaAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage#getClassDeclaration_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<JavaAnnotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' attribute.
   * @see #setClassName(String)
   * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage#getClassDeclaration_ClassName()
   * @model
   * @generated
   */
  String getClassName();

  /**
   * Sets the value of the '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassName <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' attribute.
   * @see #getClassName()
   * @generated
   */
  void setClassName(String value);

  /**
   * Returns the value of the '<em><b>Class Injection Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Injection Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Injection Declaration</em>' containment reference.
   * @see #setClassInjectionDeclaration(ClassInjectionDeclaration)
   * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage#getClassDeclaration_ClassInjectionDeclaration()
   * @model containment="true"
   * @generated
   */
  ClassInjectionDeclaration getClassInjectionDeclaration();

  /**
   * Sets the value of the '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassInjectionDeclaration <em>Class Injection Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Injection Declaration</em>' containment reference.
   * @see #getClassInjectionDeclaration()
   * @generated
   */
  void setClassInjectionDeclaration(ClassInjectionDeclaration value);

  /**
   * Returns the value of the '<em><b>Method Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.moflon.emf.injection.injectionLanguage.MethodDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method Declarations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Declarations</em>' containment reference list.
   * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguagePackage#getClassDeclaration_MethodDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<MethodDeclaration> getMethodDeclarations();

} // ClassDeclaration
