/**
 * generated by Xtext 2.14.0
 */
package org.moflon.emf.injection.injectionLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.moflon.emf.injection.injectionLanguage.InjectionLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface InjectionLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "injectionLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.moflon.org/emf/injection/InjectionLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "injectionLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  InjectionLanguagePackage eINSTANCE = org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl <em>Injection File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getInjectionFile()
   * @generated
   */
  int INJECTION_FILE = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INJECTION_FILE__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Class Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INJECTION_FILE__CLASS_DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Injection File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INJECTION_FILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.RegularImportImpl <em>Regular Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.RegularImportImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getRegularImport()
   * @generated
   */
  int REGULAR_IMPORT = 1;

  /**
   * The feature id for the '<em><b>Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_IMPORT__NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Regular Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.StaticImportImpl <em>Static Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.StaticImportImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getStaticImport()
   * @generated
   */
  int STATIC_IMPORT = 2;

  /**
   * The feature id for the '<em><b>Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_IMPORT__NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Static Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ClassDeclarationImpl <em>Class Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.ClassDeclarationImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getClassDeclaration()
   * @generated
   */
  int CLASS_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECLARATION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECLARATION__CLASS_NAME = 1;

  /**
   * The feature id for the '<em><b>Class Injection Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECLARATION__CLASS_INJECTION_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Method Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECLARATION__METHOD_DECLARATIONS = 3;

  /**
   * The number of structural features of the '<em>Class Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECLARATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.JavaAnnotationImpl <em>Java Annotation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.JavaAnnotationImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getJavaAnnotation()
   * @generated
   */
  int JAVA_ANNOTATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ANNOTATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ANNOTATION__PARAMETER = 1;

  /**
   * The number of structural features of the '<em>Java Annotation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ANNOTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ClassInjectionDeclarationImpl <em>Class Injection Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.ClassInjectionDeclarationImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getClassInjectionDeclaration()
   * @generated
   */
  int CLASS_INJECTION_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_INJECTION_DECLARATION__BODY = 0;

  /**
   * The number of structural features of the '<em>Class Injection Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_INJECTION_DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.MethodDeclarationImpl <em>Method Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.MethodDeclarationImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getMethodDeclaration()
   * @generated
   */
  int METHOD_DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Method Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECLARATION__METHOD_NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECLARATION__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECLARATION__BODY = 2;

  /**
   * The number of structural features of the '<em>Method Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECLARATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ParameterDeclarationImpl <em>Parameter Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.moflon.emf.injection.injectionLanguage.impl.ParameterDeclarationImpl
   * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getParameterDeclaration()
   * @generated
   */
  int PARAMETER_DECLARATION = 7;

  /**
   * The feature id for the '<em><b>Parameter Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DECLARATION__PARAMETER_TYPE = 0;

  /**
   * The feature id for the '<em><b>Parameter Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DECLARATION__PARAMETER_NAME = 1;

  /**
   * The number of structural features of the '<em>Parameter Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DECLARATION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.InjectionFile <em>Injection File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Injection File</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.InjectionFile
   * @generated
   */
  EClass getInjectionFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.moflon.emf.injection.injectionLanguage.InjectionFile#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.InjectionFile#getImports()
   * @see #getInjectionFile()
   * @generated
   */
  EReference getInjectionFile_Imports();

  /**
   * Returns the meta object for the containment reference '{@link org.moflon.emf.injection.injectionLanguage.InjectionFile#getClassDeclaration <em>Class Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.InjectionFile#getClassDeclaration()
   * @see #getInjectionFile()
   * @generated
   */
  EReference getInjectionFile_ClassDeclaration();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.RegularImport <em>Regular Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regular Import</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.RegularImport
   * @generated
   */
  EClass getRegularImport();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.RegularImport#getNamespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Namespace</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.RegularImport#getNamespace()
   * @see #getRegularImport()
   * @generated
   */
  EAttribute getRegularImport_Namespace();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.StaticImport <em>Static Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Import</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.StaticImport
   * @generated
   */
  EClass getStaticImport();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.StaticImport#getNamespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Namespace</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.StaticImport#getNamespace()
   * @see #getStaticImport()
   * @generated
   */
  EAttribute getStaticImport_Namespace();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration <em>Class Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassDeclaration
   * @generated
   */
  EClass getClassDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getAnnotations()
   * @see #getClassDeclaration()
   * @generated
   */
  EReference getClassDeclaration_Annotations();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class Name</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassName()
   * @see #getClassDeclaration()
   * @generated
   */
  EAttribute getClassDeclaration_ClassName();

  /**
   * Returns the meta object for the containment reference '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassInjectionDeclaration <em>Class Injection Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class Injection Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getClassInjectionDeclaration()
   * @see #getClassDeclaration()
   * @generated
   */
  EReference getClassDeclaration_ClassInjectionDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getMethodDeclarations <em>Method Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Method Declarations</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassDeclaration#getMethodDeclarations()
   * @see #getClassDeclaration()
   * @generated
   */
  EReference getClassDeclaration_MethodDeclarations();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.JavaAnnotation <em>Java Annotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Java Annotation</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.JavaAnnotation
   * @generated
   */
  EClass getJavaAnnotation();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.JavaAnnotation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.JavaAnnotation#getName()
   * @see #getJavaAnnotation()
   * @generated
   */
  EAttribute getJavaAnnotation_Name();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.JavaAnnotation#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parameter</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.JavaAnnotation#getParameter()
   * @see #getJavaAnnotation()
   * @generated
   */
  EAttribute getJavaAnnotation_Parameter();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.ClassInjectionDeclaration <em>Class Injection Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Injection Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassInjectionDeclaration
   * @generated
   */
  EClass getClassInjectionDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.ClassInjectionDeclaration#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Body</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ClassInjectionDeclaration#getBody()
   * @see #getClassInjectionDeclaration()
   * @generated
   */
  EAttribute getClassInjectionDeclaration_Body();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.MethodDeclaration <em>Method Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.MethodDeclaration
   * @generated
   */
  EClass getMethodDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getMethodName <em>Method Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method Name</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getMethodName()
   * @see #getMethodDeclaration()
   * @generated
   */
  EAttribute getMethodDeclaration_MethodName();

  /**
   * Returns the meta object for the containment reference list '{@link org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getParameters()
   * @see #getMethodDeclaration()
   * @generated
   */
  EReference getMethodDeclaration_Parameters();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Body</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.MethodDeclaration#getBody()
   * @see #getMethodDeclaration()
   * @generated
   */
  EAttribute getMethodDeclaration_Body();

  /**
   * Returns the meta object for class '{@link org.moflon.emf.injection.injectionLanguage.ParameterDeclaration <em>Parameter Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Declaration</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ParameterDeclaration
   * @generated
   */
  EClass getParameterDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.ParameterDeclaration#getParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parameter Type</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ParameterDeclaration#getParameterType()
   * @see #getParameterDeclaration()
   * @generated
   */
  EAttribute getParameterDeclaration_ParameterType();

  /**
   * Returns the meta object for the attribute '{@link org.moflon.emf.injection.injectionLanguage.ParameterDeclaration#getParameterName <em>Parameter Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parameter Name</em>'.
   * @see org.moflon.emf.injection.injectionLanguage.ParameterDeclaration#getParameterName()
   * @see #getParameterDeclaration()
   * @generated
   */
  EAttribute getParameterDeclaration_ParameterName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  InjectionLanguageFactory getInjectionLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl <em>Injection File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionFileImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getInjectionFile()
     * @generated
     */
    EClass INJECTION_FILE = eINSTANCE.getInjectionFile();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INJECTION_FILE__IMPORTS = eINSTANCE.getInjectionFile_Imports();

    /**
     * The meta object literal for the '<em><b>Class Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INJECTION_FILE__CLASS_DECLARATION = eINSTANCE.getInjectionFile_ClassDeclaration();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.RegularImportImpl <em>Regular Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.RegularImportImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getRegularImport()
     * @generated
     */
    EClass REGULAR_IMPORT = eINSTANCE.getRegularImport();

    /**
     * The meta object literal for the '<em><b>Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGULAR_IMPORT__NAMESPACE = eINSTANCE.getRegularImport_Namespace();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.StaticImportImpl <em>Static Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.StaticImportImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getStaticImport()
     * @generated
     */
    EClass STATIC_IMPORT = eINSTANCE.getStaticImport();

    /**
     * The meta object literal for the '<em><b>Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATIC_IMPORT__NAMESPACE = eINSTANCE.getStaticImport_Namespace();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ClassDeclarationImpl <em>Class Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.ClassDeclarationImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getClassDeclaration()
     * @generated
     */
    EClass CLASS_DECLARATION = eINSTANCE.getClassDeclaration();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECLARATION__ANNOTATIONS = eINSTANCE.getClassDeclaration_Annotations();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_DECLARATION__CLASS_NAME = eINSTANCE.getClassDeclaration_ClassName();

    /**
     * The meta object literal for the '<em><b>Class Injection Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECLARATION__CLASS_INJECTION_DECLARATION = eINSTANCE.getClassDeclaration_ClassInjectionDeclaration();

    /**
     * The meta object literal for the '<em><b>Method Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECLARATION__METHOD_DECLARATIONS = eINSTANCE.getClassDeclaration_MethodDeclarations();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.JavaAnnotationImpl <em>Java Annotation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.JavaAnnotationImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getJavaAnnotation()
     * @generated
     */
    EClass JAVA_ANNOTATION = eINSTANCE.getJavaAnnotation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JAVA_ANNOTATION__NAME = eINSTANCE.getJavaAnnotation_Name();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JAVA_ANNOTATION__PARAMETER = eINSTANCE.getJavaAnnotation_Parameter();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ClassInjectionDeclarationImpl <em>Class Injection Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.ClassInjectionDeclarationImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getClassInjectionDeclaration()
     * @generated
     */
    EClass CLASS_INJECTION_DECLARATION = eINSTANCE.getClassInjectionDeclaration();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_INJECTION_DECLARATION__BODY = eINSTANCE.getClassInjectionDeclaration_Body();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.MethodDeclarationImpl <em>Method Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.MethodDeclarationImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getMethodDeclaration()
     * @generated
     */
    EClass METHOD_DECLARATION = eINSTANCE.getMethodDeclaration();

    /**
     * The meta object literal for the '<em><b>Method Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DECLARATION__METHOD_NAME = eINSTANCE.getMethodDeclaration_MethodName();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DECLARATION__PARAMETERS = eINSTANCE.getMethodDeclaration_Parameters();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DECLARATION__BODY = eINSTANCE.getMethodDeclaration_Body();

    /**
     * The meta object literal for the '{@link org.moflon.emf.injection.injectionLanguage.impl.ParameterDeclarationImpl <em>Parameter Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.moflon.emf.injection.injectionLanguage.impl.ParameterDeclarationImpl
     * @see org.moflon.emf.injection.injectionLanguage.impl.InjectionLanguagePackageImpl#getParameterDeclaration()
     * @generated
     */
    EClass PARAMETER_DECLARATION = eINSTANCE.getParameterDeclaration();

    /**
     * The meta object literal for the '<em><b>Parameter Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DECLARATION__PARAMETER_TYPE = eINSTANCE.getParameterDeclaration_ParameterType();

    /**
     * The meta object literal for the '<em><b>Parameter Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DECLARATION__PARAMETER_NAME = eINSTANCE.getParameterDeclaration_ParameterName();

  }

} //InjectionLanguagePackage
