/**
 * generated by Xtext 2.11.0
 */
package org.moflon.emf.injection.ide;

import org.eclipse.xtext.util.Modules2;
import org.moflon.emf.injection.InjectionLanguageRuntimeModule;
import org.moflon.emf.injection.InjectionLanguageStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class InjectionLanguageIdeSetup extends InjectionLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    InjectionLanguageRuntimeModule _injectionLanguageRuntimeModule = new InjectionLanguageRuntimeModule();
    InjectionLanguageIdeModule _injectionLanguageIdeModule = new InjectionLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_injectionLanguageRuntimeModule, _injectionLanguageIdeModule));
  }
}
