/*
 * generated by Xtext 2.27.0
 */
package org.moflon.tgg.mosl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.moflon.tgg.mosl.TGGRuntimeModule;
import org.moflon.tgg.mosl.TGGStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TGGIdeSetup extends TGGStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TGGRuntimeModule(), new TGGIdeModule()));
	}
	
}
